---
- name: Stand Up BIG-IP
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false

  tasks:
  - name: Set VLAN tag
   bigip_vlan:
     name: net1
     tag: 2345
   delegate_to: localhost

  - name: Add VLAN 4093 as tagged to interface 1.1
    bigip_vlan:
     tagged_interface: 1.1
     name: net1
     tag: 4093
   delegate_to: localhost

  - name: Add VLAN 4094 as tagged to interfaces 1.1 and 1.2
    bigip_vlan:
      tagged_interfaces:
       - 1.1
       - 1.2
      name: net1
      tag: 4094
    delegate_to: localhost
