---
- name: Stand Up BIG-IP
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false

  tasks:
  #Criar partição utilizando Route Domain Default
  - name: Create partition "foo" using the default route domain
    bigip_partition:
      name: foo
    
#Criar partição utilizando Route Domain diferente do default
- name: Create partition "bar" using a custom route domain
  bigip_partition:
    name: bar
    route_domain: 3

#Alterar partição 
- name: Change route domain of partition "foo"
  bigip_partition:
    name: foo
    route_domain: 8

#Criar uma descrição para a partição
- name: Set a description for partition "foo"
  bigip_partition:
    name: foo
    description: Tenant CompanyA

#Deletar partição 
- name: Delete the "foo" partition
  bigip_partition:
    name: foo
    state: absent
