---
- name: Create BIG-IP App
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false
  
  tasks:    
  - name: Create monitor F5 Training HTTP
    bigip_monitor_http:
      name: http_f5trn_mon
      send: GET /index.php\r\n
      receive: Server [1-5]

  - name: Create monitor F5 Training HTTPS
    bigip_monitor_https:
      name: https_f5trn_mon
      send: GET /index.php\r\n
      receive: Server [1-5]
  
  - name: Create monitor vLab HTTP
    bigip_monitor_http:
      name: http_vlab_mon
      send: GET /HealthCheck.html\r\n
      receive: SERVER_UP

  - name: Create monitor F5 Training HTTPS
    bigip_monitor_https:
      name: https_vlab_mon
      send: GET /HealthCheck.html\r\n
      receive: SERVER_UP
      
