---
- name: Create BIG-IP App
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false
  
  tasks:    
  - name: Create monitor
    bigip_monitor_http:
      name: app.mon
      send: GET /
      receive: If you see this
