---
- name: Stand Up BIG-IP
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false

  tasks:
  - name: Create Pool
    bigip_pool:
      name: app01.pool
      monitors: app.mon

  - name: Add pool member
    bigip_pool_member:
      pool: app01.pool
      host: "{{ item }}"
      port: 80
    with_items:
    - 172.16.20.1
    - 172.16.20.2
    - 172.16.20.3
    - 172.16.20.4
    - 172.16.20.5
