---
- name: Stand Up BIG-IP
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false

  tasks:
  - name: Create Pool HTTP
    bigip_pool:
      name: http_pool
      monitors: app.mon

  - name: Add pool member HTTP
    bigip_pool_member:
      pool: http_pool
      host: "{{ item }}"
      port: 80
    with_items:
    - 172.16.20.1
    - 172.16.20.2
    - 172.16.20.3
    - 172.16.20.4
    - 172.16.20.5

  - name: Create Pool HTTPS
    bigip_pool:
      name: https_pool
      monitors:
      - https

  - name: Add pool member HTTPS
    bigip_pool_member:
      pool: https_pool
      host: "{{ item }}"
      port: 443
    with_items:
    - 172.16.20.1
    - 172.16.20.2
    - 172.16.20.3
    - 172.16.20.4
    - 172.16.20.5

  - name: Create Pool ASM
    bigip_pool:
      name: hack.pool
      monitors: app.mon

  - name: Add pool member to ASM
    bigip_pool_member:
      pool: hack.pool
      host: "{{ item }}"
      port: 80
    with_items:
    - 172.16.20.100
