---
- name: Stand Up BIG-IP
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false

  tasks:
  - name: Add virtual server
    bigip_virtual_server:
      state: present
      partition: Common
      name: http_vs
      destination: 10.1.10.10
      port: 443
      pool: app01.pool
      snat: Automap
      description: Test Virtual Server
      profiles:
       - http
    delegate_to: localhost
