---
- name: Activate BIG-IP License
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: '{{ inventory_hostname }}'
    F5_USER: '{{ admin_user }}'
    F5_PASSWORD: '{{ admin_password }}'
    F5_VALIDATE_CERTS: false
  tasks:
  - name: Activate License
    bigip_device_license:
      license_key: QABRB-WKOPD-JZTMM-KHAVB-MHSPMTM
      accept_eula: true
