---
- name: Stand Up BIG-IP
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false

  tasks:
  - name: Set Timezone and NTP Server
    bigip_device_ntp:
      timezone: America/Sao_Paulo
      ntp_servers:
      - 10.1.20.252

  - name: Set Hostname
    bigip_hostname:
      hostname: bigip.f5trn.com
  
  - name: Set DNS
    bigip_device_dns:
      name_servers:
      - 8.8.8.8
      search:
      - f5trn.com
  
  - name: Criar VLAN internal
    bigip_vlan:
      name: vlan.internal
      untagged_interface: 1.2
      tag: 4093

  - name: Criar Self IP internal
    bigip_selfip:
      name: 10.1.20.241
      vlan: vlan.internal
      address: 10.1.20.241
      netmask: 255.255.255.0
      allow_service: all

  - name: Criar External VLAN
    bigip_vlan:
      name: vlan.external
      untagged_interface: 1.1
      tag: 4094

  - name: Criar Self IP external
    bigip_selfip:
      name: 10.1.10.241
      vlan: vlan.external
      address: 10.1.10.241
      netmask: 255.255.255.0
      allow_service: none   

  - name: Save Sys config
    bigip_config:
      save: true

  - name: Disable the Setup Utility
    bigip_sys_global:
      gui_setup: no    

#  - name: Provisionar LTM
#    bigip_provision:
#      module: ltm
#      level: nominal

#  - name: Aguarde finalizando o provisionamento
#    pause:
#      seconds: 120    

#  - name: Change User Passwords
#    bigip_user:
#      username_credential: "{{ item.user }}"
#      password_credential: "{{ item.passwd }}"
#    loop:
#      - user: "{{ ansible_ssh_user }}"
#        passwd: "{{ ansible_ssh_pass }}"
#      - user: "{{ admin_user }}"
#        passwd: "{{ admin_password }}"
