---
- name: Stand Up BIG-IP
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false

  tasks:
  - name: Set Timezone and NTP Server
    bigip_device_ntp:
      timezone: America/Sao_Paulo
      ntp_servers:
      - 10.244.3.69
      - 10.244.3.60

  - name: Set Hostname
    bigip_hostname:
      hostname: TVT-DC-ASM-01.original.com.br
  
  - name: Set DNS
    bigip_device_dns:
      name_servers:
      - 10.244.3.246
      - 10.244.3.249
      search:
      - original.com.br
  
  - name: Criar VLAN Transito 2956
    bigip_vlan:
      name: TRANS_2956
      untagged_interface: 1.1
      tag: 2956

  - name: Criar Self IP Transito 2956
    bigip_selfip:
      name: self_2956
      vlan: TRANS_2956
      address: 10.106.0.9
      netmask: 255.255.255.248
      allow_service: none

#  - name: Create Internal VLAN
#    bigip_vlan:
#      name: internal.vlan
#      untagged_interface: 1.1
#      tag: 4094#

#  - name: Create internal Self IP
#    bigip_selfip:
#      name: internal.self
#      vlan: internal.vlan
#      address: 172.16.0.35
#      netmask: 255.255.0.0
#      allow_service: all    

  - name: Save Sys config
    bigip_config:
      save: true

  - name: Disable the Setup Utility
    bigip_sys_global:
      gui_setup: no    

  - name: Provisionar LTM
    bigip_provision:
      module: ltm
      level: nominal

  - name: Provisionar ASM
    bigip_provision:
      module: asm
      level: nominal

  - name: Aguarde finalizando o provisionamento
    pause:
      seconds: 120    

  - name: Change User Passwords
    bigip_user:
      username_credential: "{{ item.user }}"
      password_credential: "{{ item.passwd }}"
    loop:
      - user: "{{ ansible_ssh_user }}"
        passwd: "{{ ansible_ssh_pass }}"
      - user: "{{ admin_user }}"
        passwd: "{{ admin_password }}"
