---
- name: Revoke BIG-IP License
  hosts: big-ips
  gather_facts: false
  connection: local
  environment:
    F5_SERVER: "{{ inventory_hostname }}"
    F5_USER: "{{ admin_user }}"
    F5_PASSWORD: "{{ admin_default_password}}"
    F5_VALIDATE_CERTS: false
  tasks:
  - name: Revoke License
    bigip_device_license:
      state: absent
      
